nav:
  - Overview:
      - "What is earthaccess?": "index.md"
      - "Community calendar": "calendar.md"
      - "External resources": "resources.md"
      - "About us": "about-us.md"
      - "Supported by": "supported-by.md"
      - Governance:
          - Decisions: "governance/decisions/"

  - API reference:
      - Search and Access: "api/index.md"
      - Modules:
          - Collections:
              - "Collection queries": "api/collections/collections-query.md"
              - "Collection results": "api/collections/collections.md"
              - "Collection services": "api/collections/collections-services.md"
          - Granules:
              - "Granule queries": "api/granules/granules-query.md"
              - "Granule results": "api/granules/granules.md"
          - Store:
              - "Store": "api/store/store.md"
          - Auth:
              - "Auth": "api/auth/auth.md"

  - User guide:
      - "user/index.md"
      - "Quick start": "user/quick-start.md"
      - How-to:
          - "Authenticate with Earthdata Login": "user/howto/authenticate.md"
          - "Search for data using filters": "user/howto/search-granules.md"
          - "Access data": "user/howto/access-data.md"
          - "Using authenticated sessions to access data": "user/howto/edl.ipynb"
          # - "Download data from on-prem location": "user/howto/onprem.md"
          - "Direct S3 access - Open/stream files in the cloud": "user/howto/cloud.md"
          - "Search for services": "user/howto/search-services.md"
          - "Visualize granules": "user/howto/visualize-granules.ipynb"
      - Tutorials:
          - "Accessing remote NASA data with fsspec": "user/tutorials/file-access.ipynb"
          - "Search and access of restricted datasets": "user/tutorials/restricted-datasets.ipynb"
          # - "Reproducing NASA sea level rise infographic": "tutorials/SSL.ipynb" TODO: make this faster
          - "Accessing and visualizing EMIT data with a few lines of code": "user/tutorials/emit-earthaccess.ipynb"
          - "Cloud optimized access to TEMPO air quality data with earthaccess and virtualizarr": "user/tutorials/virtual_dataset_tutorial_with_TEMPO_Level3.ipynb"
      - Explanation:
          - "Authentication": "user/explanation/authenticate.md"
          - "Status": "user/explanation/status.md"
          - "Search": "user/explanation/search.md"
          - "Access": "user/explanation/access.md"
          - "Backwards compatibility": "user/explanation/backwards-compatibility.md"
          - "Remote access and caching with earthaccess": "user/explanation/fsspec.ipynb"
      - Reference:
          - Glossary:
              - "NASA glossary": "user/reference/glossary/nasa-glossary.md"
              - "Cloud computing terminology": "user/reference/glossary/cloud-glossary.md"
  - Contributor guide:
      - "contributor/index.md" # << Link target of the parent node
      - "Code of conduct": "contributor/code-of-conduct.md"
      - How-to:
          - "Setup dev environment": "contributor/howto/development.md"
          - "Create a Pull Request (PR)": "contributor/howto/pr-guide.md"
          - "Release a version": "contributor/howto/releasing.md"
          - "Be a maintainer": "contributor/howto/maintainers-guide.md"
          - "Triage issues": "contributor/howto/triaging.md"
      - Explanation:
          - "Integration tests": "contributor/explanation/integration-tests.md"
      - Reference:
          - "Naming conventions": "contributor/reference/naming-convention.md"
